/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paintpfinal;

import java.awt.Component;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.media.CannotRealizeException;
import javax.media.Manager;
import javax.media.MediaLocator;
import javax.media.NoPlayerException;
import javax.media.Player;
import javax.swing.JOptionPane;

/**
 *
 * @author Jesus
 */
public class VentanaInternaJMFPlayer extends VentanaInterna {

    
    private Player player = null;
    private VentanaPrincipalPFinal parent;
    
    /**
     * Creates new form VentanaInternaJMFPlayer
     */
    public VentanaInternaJMFPlayer(File f,VentanaPrincipalPFinal pa) {
        initComponents();
        String sfichero = "file:" + f.getAbsolutePath();
        MediaLocator ml = new MediaLocator(sfichero);
        try {
            parent = pa;
            player = Manager.createRealizedPlayer(ml);
            Component vc = player.getVisualComponent();
            if(vc!=null)add(vc, java.awt.BorderLayout.CENTER);
            Component cpc = player.getControlPanelComponent();
            if(cpc!=null)add(cpc, java.awt.BorderLayout.SOUTH);
            this.pack();
        }catch(Exception e) {
            JOptionPane.showMessageDialog(this,"VentanaInternaJMFPlayer: "+e);
            player = null;
        }
    }
    
    
    public static VentanaInternaJMFPlayer getInstance(File f, VentanaPrincipalPFinal pa){
        VentanaInternaJMFPlayer v = new VentanaInternaJMFPlayer(f,pa);
        return (v.player!=null?v:null);
    }
    
    
    public void play() {
        if (player != null) {
            try {
                player.start();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,"VentanaInternaJMFPlayer: "+e);
            }
        }
    }
    
    public void stop() {
        if (player != null) {
            try {
                player.stop();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,"VentanaInternaJMFPlayer: "+e);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}

    
