/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sm.jrc.iu;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;

/**
 * Clase para personalizar un diálogo con una paleta de selección de colores.
 * @author Jesús Ruiz Castellano
 */
public class ElegirColor extends javax.swing.JDialog {

    /**
     * Ítem color de la paleta.
     */
    private Color color;
    
    /**
     * Variable para saber si se ha aplicado.
     */
    private boolean esAplicado;
    
    /**
     * Crea nueva forma SeleccionColor
     * @param parent : frame padre
     * @param modal : modalidad
     */
    public ElegirColor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * Método para asignar el color de la paleta.
     * @param co : color seleccionado en la paleta
     */
    public void setColor(Color co){
        color = co;
    }
    
    /**
     * Método para obtener el color.
     * @return Color - color : color de la paleta.
     */
    public Color getColor(){
        return color;
    }
    
    /**
     * Método para saber si se ha aplicado.
     * @return boolean - esAplicado, se ha aplicado el cambio.
     * true, se ha aplicado
     * false, no se ha aplicado
     */
    public boolean isAplicado(){
        return esAplicado;
    }
    
    /**
     * Método para asignar el estado de haber aplicado el cambio de color 
     * de la paleta.
     * @param apli : bandera para comprobar si se ha aplicado o no el cambio
     */
    public void setAplicado(boolean apli){
        esAplicado = apli;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paletaColores = new javax.swing.JColorChooser();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        botAplicar = new javax.swing.JButton();
        botCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Paleta de colores");
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(500, 350));

        paletaColores.setMinimumSize(new java.awt.Dimension(500, 350));
        paletaColores.setPreferredSize(new java.awt.Dimension(500, 350));
        getContentPane().add(paletaColores, java.awt.BorderLayout.CENTER);

        jPanel1.setPreferredSize(new java.awt.Dimension(807, 70));
        jPanel1.setLayout(new java.awt.BorderLayout());

        botAplicar.setText("Aplicar");
        botAplicar.setPreferredSize(new java.awt.Dimension(100, 40));
        botAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAplicarActionPerformed(evt);
            }
        });
        jPanel2.add(botAplicar);

        botCancelar.setText("Cancelar");
        botCancelar.setPreferredSize(new java.awt.Dimension(100, 40));
        botCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(botCancelar);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método Action que asigna el color seleccionado en la paleta, así como
     * pone a true el valor de esAplicado.
     * Después cierra el diálogo.
     * @param evt : evento de seleccionar el botón
     */
    private void botAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAplicarActionPerformed
        color = paletaColores.getColor();
        esAplicado = true;
        // Para cerrar la ventana una vez aplicados los cambios
        dispose();
    }//GEN-LAST:event_botAplicarActionPerformed

    /**
     * Método Action para salir del diálogo de selección de color.
     * Cierra el diálogo y pone esAplicado a false.
     * @param evt : evento de seleccionar el botón
     */
    private void botCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCancelarActionPerformed
        // Para cerrar la ventana una vez aplicados los cambios
        dispose();
        esAplicado = false;
    }//GEN-LAST:event_botCancelarActionPerformed

    /**
     * Método para cambiar el logo de la Paleta de colores.
     * @return Image retValue - Imagen obtenida a partir de la ruta especificada.
     */
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("IconosPFinal/descarga_opt.jpg"));

        return retValue;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botAplicar;
    private javax.swing.JButton botCancelar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JColorChooser paletaColores;
    // End of variables declaration//GEN-END:variables
}
