/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sm.jrc.iu;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.image.BufferedImage;

/**
 * Clase para, además de dibujar figuras, añadir una imagen sobre la que trabajar.
 * @author Jesús Ruiz Castellano
 */
public class LienzoImagen2D extends Lienzo2D {

    private BufferedImage imagen;
    
    /**
     * Crea una nueva forma LienzoImagen2D
     */
    public LienzoImagen2D() {
        initComponents();
    }

    public BufferedImage getImagen(boolean drawVect) {
        if (drawVect) {
            
            BufferedImage ImgOut = new BufferedImage (imagen.getWidth(), imagen.getHeight(), imagen.getType());
            this.paint(ImgOut.createGraphics());
            return ImgOut;
        }
        else
            return imagen;
    }

    public BufferedImage getImagen() {
        return imagen;
    }
    
    

    public void setImagen(BufferedImage img) {
        this.imagen = img;
        if(img!=null) {  
            setPreferredSize(new Dimension(img.getWidth(),img.getHeight()));
        }
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setColor(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        
        if(imagen!=null) g.drawImage(imagen,0,0,this);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
